sudo: required

services:
  - docker

steps:
- docker --version
- docker pull vineethvijay/web1
- docker run  --name test1 -itd vineethvijay/web1
- docker ps -a
- docker exec -it test1 /bin/sh -c "service apache2 status"
